apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3-compute
spec:
  compositeTypeRef:
    apiVersion: api.example.org/v1alpha1
    kind: strgcompute
  resources:
    - name: s3bucket
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        metadata:
          annotations:
            argocd.argoproj.io/tracking-id: 'bootstrap:s3.aws.upbound.io/Bucket:argocd/'
          name: crossplane-bucket-sentgitjul
        spec:
          forProvider:
            region: us-east-2
          providerConfigRef:
            name: default
